package com.example.mealmate.presenter.start_fragment_presenter;

import com.example.mealmate.presenter.start_fragment_presenter.start_fragment_presenter_interface.Start_Fragment_Presenter_Interface;

public class Start_Fragment_Presenter implements Start_Fragment_Presenter_Interface {
}